name: PHP Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Install pip Dependencies
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
         cache: 'pip'
      
      - run: |
            pip install -r requirements.txt
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install
      
      - name: Start PHP server
        run: php -S localhost:8000 &

      - name: Set up ngrok
        run: sudo snap install ngrok --devmode && ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}


      - name: forward port to web
        run: ngrok http --domain=teaching-civet-smoothly.ngrok-free.app 8000 &
      
      - run: sleep 50

      - name: Trigger next workflow
        run: gh auth login --with-token <<<"${{ secrets.WORKFLOW_TOKEN }}" && gh workflow run php-workflow.yml

      
        

  






       
