name: PHP Server

on:
  push:
    branches:
      - master
    
    
runs-on: ubuntu-latest
jobs:
  setup-php:

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install
      
      - name: Start PHP server
        run: php -S localhost:8000 &


  setup-ngrok:
    runs-on: ubuntu-latest
    needs: setup-php
    
    steps:
    
      - name: Set up ngrok
        run: sudo snap install ngrok --devmode && ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Forward port to web
        run: ngrok http --domain=feline-viable-precisely.ngrok-free.app 8000
          
  






       
