name: PHP Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      
      - name: Set up ngrok
        uses: tmshkr/ngrok-ssh@latest
        with:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: Install dependencies
        run: composer install
      
      - name: Start PHP server
        run: php -S localhost:8000 & ngrok http 8000



