name: PHP Server

on:
  push:
    branches:
      - master

jobs:
  # setup-php:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '7.4'

  #     - name: Install dependencies
  #       run: composer install
      
  #     - name: Start PHP server
  #       run: php -S localhost:8000 &
  
  setup-ngrok:
    #  needs: setup-php
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ngrok
        uses: tmshkr/ngrok-ssh@latest
        with:
          SSH_PORT: 8000
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: Start tunnel
        # run: ssh Akshat2512@0.tcp.us-cal-1.ngrok.io -p 14726
        # run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }} && ngrok http 80
        run: cat /home/runner/.config/ngrok/ngrok.yml


